//ENV

export const NEXT_PUBLIC_BACKEND = process.env.NEXT_PUBLIC_BACKEND;

export const NEXT_PUBLIC_REDIRECT_TO = process.env.NEXT_PUBLIC_REDIRECT_TO;

export const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET;

export const NEXT_PUBLIC_TYPE = process.env.NEXT_PUBLIC_TYPE;

//Google
export const NEXT_PUBLIC_GOOGLE_CLIENT_ID =
  process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

export const NEXT_PUBLIC_GOOGLE_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET;
