import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      {session && <Header />}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
